[package]
name = "tsdb-config"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
rust-ini = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
