[package]
name = "tsdb-aggregate"
version.workspace = true
edition.workspace = true

[dependencies]
tsdb-types = { workspace = true }
tsdb-config = { workspace = true }
tsdb-core = { workspace = true }
tsdb-chart = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
nng = { workspace = true }
rocksdb = { workspace = true }
tempfile = { workspace = true }
